name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
 
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16
 
      - name: Cypress.io
        uses: cypress-io/github-action@v4.2.2
        with:
          record: true
          browser: chrome
          build: npm run build
          start: npm start
        env:
          CI: true
          CYPRESS_RECORD_KEY: 78658b9b-b396-4355-a37c-63796a8fc113
