name: E2E on Chrome

on:
  push:
    branches:
      - master

jobs:
  cypress-suite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
 
      - name: Run Cypress e2e tests
        uses: cypress-io/github-action@v5.0.2
        with:
          record: true
          browser: chrome
          start: npm run cy:run --record --key=78658b9b-b396-4355-a37c-63796a8fc113 --parallel
          tag: merge master
        env:
          CI: true
          CYPRESS_RECORD_KEY: 78658b9b-b396-4355-a37c-63796a8fc113
          
